services:
  web:
    image: fastapi-boilerplate:0.1
    ports:
      - "80:8000"
    environment:
      - ENV=production
      - POSTGRES_USER=${POSTGRES_USER:-default_user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-12345678}
      - POSTGRES_HOST=postgres_db   # container name
      - POSTGRES_DB=${POSTGRES_DB:-default_database}
    depends_on:
      - postgres_db
    volumes:
      - .:/app
    networks:
      - app-network
    env_file:
      - .env

  postgres_db:
    image: postgres:15
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-default_user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-12345678}
      - POSTGRES_DB=${POSTGRES_DB:-default_database}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    env_file:
      - .env

volumes:
  postgres_data:

networks:
  app-network:
