"""empty message

Revision ID: 3bec89db21cb
Revises: 6df7e70b1abc
Create Date: 2025-04-12 16:43:14.620931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bec89db21cb'
down_revision: Union[str, None] = '6df7e70b1abc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('long', sa.Float(), nullable=False),
    sa.Column('category', sa.Enum('UNKNOWN', 'HOSPITAL', 'PHARMACY', 'PARK', 'MUSEUM', 'HOTEL', 'BANK', 'FUEL', 'ENTERTAINMENT', 'FOODMARKET', 'RESTAURANT', 'POSTOFFICE', 'ELECTRICSHOP', name='location_category'), nullable=False),
    sa.Column('wheelchair_access', sa.Boolean(), nullable=True),
    sa.Column('accessible_toilet', sa.Boolean(), nullable=True),
    sa.Column('disabled_parking', sa.Boolean(), nullable=True),
    sa.Column('braille_signs', sa.Boolean(), nullable=True),
    sa.Column('induction_loops', sa.Boolean(), nullable=True),
    sa.Column('visual_audio_signals', sa.Boolean(), nullable=True),
    sa.Column('lowered_counters', sa.Boolean(), nullable=True),
    sa.Column('assistance_service', sa.Boolean(), nullable=True),
    sa.Column('guide_paths', sa.Boolean(), nullable=True),
    sa.Column('elevator', sa.Boolean(), nullable=True),
    sa.Column('seating_with_armrests', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('locations')
    # ### end Alembic commands ###
