"""empty message

Revision ID: c684be83de4e
Revises: dfdfc5571985
Create Date: 2025-04-12 01:25:26.700267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM


# revision identifiers, used by Alembic.
revision: str = 'c684be83de4e'
down_revision: Union[str, None] = 'dfdfc5571985'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

disability_enum = ENUM(
    'WHEELCHAIR', 'HEARING', 'VISION', 'COGNITIVE', 'NONE',
    name='disabilitytype',
    create_type=False  # We'll create it manually
)

def upgrade() -> None:
    # First, create the enum type in PostgreSQL
    disability_enum.create(op.get_bind())

    # Then add the column using the newly created type
    op.add_column(
        'users',
        sa.Column('disability_type', disability_enum, nullable=False)
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'disability_type')
    # ### end Alembic commands ###
